# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main # runs when a change is made to the main branch

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macOS-latest'
    windows:
      imageName: 'windows-latest'
  maxParallel: 2

pool:
  vmImage: $(imageName)

stages:
  - stage:
    displayName: 'Useless Stage New'
    jobs:
      - job:
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '10.x'
            displayName: 'Install Node.js'

          - task: Npm@1
            inputs:
              command: 'ci'
            displayName: 'Install Packages'

          - task: Npm@1
            inputs:
              command: 'custom'
              customCommand: 'run lint'
            displayName: 'Lint'

          - task: Npm@1
            inputs:
              command: 'custom'
              customCommand: 'run test'
            displayName: 'Test'
